from __future__ import annotations

from fastapi import FastAPI
from fastapi.testclient import TestClient

from openjarvis.morning_briefing import MorningBriefingService, NewsItem
from openjarvis.server.startup_routes import startup_router
from openjarvis.startup.launchagent import LaunchAgentManager
from openjarvis.startup.models import LaunchAgentConfig
from openjarvis.startup.scheduler import StartupScheduler
from openjarvis.startup.service import StartupService
from openjarvis.startup.state import StartupStateStore


class FakeFetcher:
    def fetch(self, *, max_items: int = 12) -> list[NewsItem]:
        return [
            NewsItem(
                title="Route briefing",
                summary="Generated by a local fake fetcher.",
                source_url="https://example.test/route",
                source_name="Example",
            )
        ]


def test_startup_status_install_remove_and_manual_trigger(tmp_path) -> None:
    app = FastAPI()
    state = StartupStateStore(tmp_path / "state")
    app.state.morning_briefing_service = MorningBriefingService(
        db_path=tmp_path / "briefing.db",
        news_fetcher=FakeFetcher(),
    )
    app.state.startup_service = StartupService(
        state_store=state,
        launch_agent=LaunchAgentManager(
            config=LaunchAgentConfig(
                label="com.openjarvis.test",
                program_arguments=["/bin/echo", "jarvis"],
            ),
            launch_agents_dir=tmp_path / "LaunchAgents",
        ),
        scheduler=StartupScheduler(state),
        morning_briefing_service=app.state.morning_briefing_service,
    )
    app.include_router(startup_router)
    client = TestClient(app)

    status = client.get("/v1/startup/status")
    assert status.status_code == 200
    assert status.json()["external_telemetry"] is False
    assert status.json()["scheduler"]["background_loop"] is False

    installed = client.post("/v1/startup/install")
    assert installed.status_code == 200
    assert installed.json()["launch_at_login"] is True

    triggered = client.post("/v1/startup/morning-briefing", json={"force": True})
    assert triggered.status_code == 200
    assert triggered.json()["triggered"] is True
    assert triggered.json()["briefing"]["title"].startswith("Morning Briefing")

    removed = client.post("/v1/startup/remove")
    assert removed.status_code == 200
    assert removed.json()["launch_at_login"] is False
